
.. raw:: html

   <script type="text/javascript">var switchTo5x=true;</script>
   <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
   <script type="text/javascript">
        stLight.options({
                publisher:'1d7ca932-4e5f-4b05-bf05-3b2bc0db846d'
        });
   </script>   

   <span class="st_sharethis"></span>
   <span class="st_facebook"></span>
   <span class="st_twitter"></span>
   <span class="st_meneame"></span>
   <span class="st_digg"></span>
   <span class="st_delicious"></span>
   <span class="st_blogger"></span>
   <span class="st_stumbleupon"></span>
   <span class="st_gbuzz"></span>
   <span class="st_email"></span>
   <script type="text/javascript" src="https://apis.google.com/js/plusone.js">{lang: 'es-419'}</script><g:plusone size="small" annotation="inline"></g:plusone>
   
