.. _Peperino Pómoro: http://es.wikipedia.org/wiki/Peperino_P%C3%B3moro
.. _Cha Cha Cha: https://es.wikipedia.org/wiki/Cha_cha_cha_(programa_de_televisión)

.. _Gloria Carrá: http://www.imdb.com/name/nm0139910/
.. .. _Gloria Trevi: http://www.imdb.com/name/nm0872381/
.. _Gloria Trevi: http://es.wikipedia.org/wiki/Gloria_Trevi
.. _Gloria Estefan: http://es.wikipedia.org/wiki/Gloria_Stefan
.. _Gloria Gaynor: http://es.wikipedia.org/wiki/Gloria_Gaynor
.. _Daniel Tinayre: http://www.imdb.com/name/nm0863853/
.. _Moria Casán: http://www.imdb.com/name/nm0145784/
.. _Vesre: http://es.wikipedia.org/wiki/Vesre
.. _Sofía Gala: http://www.imdb.com/name/nm1078686/
.. _Shakira: http://es.wikipedia.org/wiki/Shakira
.. _Divina Gloria: http://es.wikipedia.org/wiki/Divina_Gloria
.. _Divine Brown: http://en.wikipedia.org/wiki/Divine_Brown_%28sex_worker%29
.. _Juana Viale Del Carril: http://www.imdb.com/name/nm1403777/
.. _Daniel Hadad: http://es.wikipedia.org/wiki/Daniel_Hadad
.. _Rolo Puente: http://www.imdb.com/name/nm0699921/
.. _Carlos Balá: http://es.wikipedia.org/wiki/Carlos_Bal%C3%A1

-----

Volver al :doc:`índice de sermones de Peperino <peperino>`

.. include:: humor_pie.inc
