.. role:: subrayado

..
   |randi| image:: randi2.jpg
   :alt: James Randi
   :width: 150
   :height: 180
   :align: right

.. _jref: http://www.randi.org


.. |firmarandi| image:: signature.gif
    :alt: (Firma de James Randi)
    :height: 84
    :width: 165

..
    .. |pound|  unicode:: U+000A3 .. POUND SIGN

.. # Siglas

.. |jref| raw:: html

   <acronym title="James Randi Educational Foundation">JREF</acronym>

.. |OVNI| raw:: html

   <acronym title="objeto volador no identificado">OVNI</acronym>

.. |OVNIs| raw:: html

   <acronym title="objetos voladores no identificados">OVNIs</acronym>

.. |fda| raw:: html

   <acronym title="Food and Drug Administration">FDA</acronym>

.. |cicap| raw:: html

   <acronym title="Comitato Italiano per il Controllo delle Affermazioni sul Paranormale">CICAP</acronym>

.. |usd| raw:: html

   <acronym title="dólares estadounidenses">$</acronym>

.. |gbp| raw:: html

   <acronym title="libras esterlinas">GBP</acronym>

.. |ftc| raw:: html

   <acronym title="Federal Trade Commission (Comisión Federal de Comercio de EE.UU.)">FTC</acronym>

.. |pes| raw:: html

   <acronym title="percepción extrasensorial">PES</acronym>

.. |tam| raw:: html

   <acronym title="The Amaz!ng Meeting">TAM</acronym>

.. |aps| raw:: html

   <acronym title="American Physics Society">APS</acronym>

